<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <meta name="author" content="Vu Anh">
        
        <link rel="shortcut icon" href="../img/favicon.ico">
        <title>Error Handling - Java</title>
        <link href="../css/bootstrap-custom.min.css" rel="stylesheet">
        <link href="../css/font-awesome-4.5.0.css" rel="stylesheet">
        <link href="../css/base.css" rel="stylesheet">
        <link rel="stylesheet" href="../css/highlight.css">
        <link href="../components/magiz-c-book/src/book.css" rel="stylesheet">
        <link href="../components/magiz-c-course/src/course.css" rel="stylesheet">
        <link href="../components/magiz-c-video/src/video.css" rel="stylesheet">
        <link href="../components/magiz-c-benchmark/src/benchmark.css" rel="stylesheet">
        <link href="../components/magiz-c-paper/src/paper.css" rel="stylesheet">
        <link href="../components/magiz-doc/style.css" rel="stylesheet">
        <link href="../components/magiz-doc/highlight.css" rel="stylesheet">
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
	
	<script src="../js/jquery-1.10.2.min.js"></script>
        <script src="../js/bootstrap-3.0.3.min.js"></script>
        <script src="../js/highlight.pack.js"></script>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-68978617-1', 'magizbox.com');
            ga('send', 'pageview');
        </script> 
    </head>

    <body>

        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">

        <!-- Collapsed navigation -->
        <div class="navbar-header">
            <!-- Expander button -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="..">Java</a>
        </div>

        <!-- Expanded navigation -->
        <div class="navbar-collapse collapse">
                <!-- Main navigation -->
                <ul class="nav navbar-nav">
                    <li >
                        <a href=".."><span class='fa fa-home'></span> Home</a>
                    </li>
                    <li >
                        <a href="../get_started/"><span class='fa fa-cloud-download'></span> Get Started</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='fa fa-book'></span> Basic <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            
<li >
    <a href="../basic_syntax/">Basic Syntax: print, conditional, loop, function</a>
</li>
                            
<li >
    <a href="../data_structure/">Data Structure (number, string, collection, datetime)</a>
</li>
                            
  <li class="dropdown-submenu">
    <a href="#">OOP</a>
    <ul class="dropdown-menu">
            
<li >
    <a href="../oop/">Classes and Objects</a>
</li>
            
<li >
    <a href="../oop_encapsulation/">Encapsulation</a>
</li>
            
<li >
    <a href="../oop_inheritance/">Inheritance</a>
</li>
            
<li >
    <a href="../oop_polymorphism/">Polymorphism</a>
</li>
            
<li >
    <a href="../oop_abstraction/">Abstraction</a>
</li>
    </ul>
  </li>
                            
<li >
    <a href="../io/">Files & IO</a>
</li>
                        </ul>
                    </li>
                    <li class="dropdown active">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='fa fa-book'></span> Software Development <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            
<li class="active">
    <a href="./">Error Handling</a>
</li>
                            
<li >
    <a href="../logging/">Logging</a>
</li>
                            
<li >
    <a href="../ide/">IDE</a>
</li>
                            
<li >
    <a href="../package_manager/">Package Manager</a>
</li>
                            
<li >
    <a href="../build_tool/">Build Tool</a>
</li>
                            
<li >
    <a href="../production/">Production</a>
</li>
                        </ul>
                    </li>
                </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#" data-toggle="modal" data-target="#mkdocs_search_modal">
                        <i class="fa fa-search"></i> Search
                    </a>
                </li>
                    <li >
                        <a rel="next" href="../io/">
                            <i class="fa fa-arrow-left"></i> Previous
                        </a>
                    </li>
                    <li >
                        <a rel="prev" href="../logging/">
                            Next <i class="fa fa-arrow-right"></i>
                        </a>
                    </li>
            </ul>
        </div>
    </div>
</div>

        <div class="container">
                <div class="col-md-3"><div class="bs-sidebar hidden-print affix well" role="complementary">
    <ul class="nav bs-sidenav">
        <li class="main active"><a href="#type-of-exceptions">Type of exceptions</a></li>
        <li class="main "><a href="#exception-hierarchy">Exception Hierarchy</a></li>
        <li class="main "><a href="#exceptions-methods">Exceptions Methods</a></li>
        <li class="main "><a href="#catching-exceptions">Catching Exceptions</a></li>
        <li class="main "><a href="#multiple-catch-blocks">Multiple Catch Blocks</a></li>
        <li class="main "><a href="#catching-multiple-type-of-exceptions">Catching Multiple Type of Exceptions</a></li>
        <li class="main "><a href="#the-throwsthrow-keywords">The Throws/Throw Keywords</a></li>
        <li class="main "><a href="#the-finally-block">The Finally Block</a></li>
        <li class="main "><a href="#the-try-with-resources">The try-with-resources</a></li>
        <li class="main "><a href="#user-defined-exceptions">User-defined Exceptions</a></li>
        <li class="main "><a href="#common-exceptions">Common Exceptions</a></li>
        <li class="main "><a href="#suggested-readings">Suggested Readings</a></li>
    </ul>
</div></div>
                <div class="col-md-9" role="main">

<p>An exception (or exceptional event) is a problem that arises during the execution of a program. When an <strong>Exception</strong> occurs the normal flow of the program is disrupted and the program/Application terminates abnormally, which is not recommended, therefore, these exceptions are to be handled.</p>
<p>An exception can occur for many different reasons. Following are some scenarios where an exception occurs.</p>
<ul>
<li>A user has entered an invalid data.</li>
<li>A file that needs to be opened cannot be found.</li>
<li>A network connection has been lost in the middle of communications or the JVM has run out of memory.</li>
</ul>
<p>Some of these exceptions are caused by user error, others by programmer error, and others by physical resources that have failed in some manner.</p>
<p>Based on these, we have three categories of Exceptions. You need to understand them to know how exception handling works in Java.</p>
<h2 id="type-of-exceptions">Type of exceptions</h2>
<p><strong>Checked Exception</strong></p>
<p>A checked exception is an exception that occurs at the compile time, these are also called as compile time exceptions. These exceptions cannot simply be ignored at the time of compilation, the programmer should take care of (handle) these exceptions.</p>
<p>For example, if you use FileReader class in your program to read data from a file, if the file specified in its constructor doesn't exist, then a FileNotFoundException occurs, and the compiler prompts the programmer to handle the exception.</p>
<pre><code class="java">import java.io.File;
import java.io.FileReader;

public class FilenotFound_Demo {

   public static void main(String args[]) {     
      File file = new File(&quot;E://file.txt&quot;);
      FileReader fr = new FileReader(file); 
   }
}
</code></pre>

<p>If you try to compile the above program, you will get the following exceptions.</p>
<pre><code>C:\&gt;javac FilenotFound_Demo.java
FilenotFound_Demo.java:8: error: unreported exception FileNotFoundException; must be caught or declared to be thrown
      FileReader fr = new FileReader(file);
                      ^
1 error
</code></pre>

<p>Note âˆ’ Since the methods <strong>read()</strong> and <strong>close()</strong> of FileReader class throws IOException, you can observe that the compiler notifies to handle IOException, along with FileNotFoundException.</p>
<p><strong>Unchecked exceptions</strong></p>
<p>An unchecked exception is an exception that occurs at the time of execution. These are also called as <strong>Runtime Exceptions</strong>. These include programming bugs, such as logic errors or improper use of an API. Runtime exceptions are ignored at the time of compilation.</p>
<p>For example, if you have declared an array of size 5 in your program, and trying to call the 6th element of the array then an <em>ArrayIndexOutOfBoundsExceptionexception</em> occurs.</p>
<pre><code class="java">public class Unchecked_Demo {

   public static void main(String args[]) {
      int num[] = {1, 2, 3, 4};
      System.out.println(num[5]);
   }
}
</code></pre>

<p>If you compile and execute the above program, you will get the following exception.</p>
<pre><code>Exception in thread &quot;main&quot; java.lang.ArrayIndexOutOfBoundsException: 5
    at Exceptions.Unchecked_Demo.main(Unchecked_Demo.java:8)
</code></pre>

<p><strong>Errors</strong></p>
<p>These are not exceptions at all, but problems that arise beyond the control of the user or the programmer. Errors are typically ignored in your code because you can rarely do anything about an error. For example, if a stack overflow occurs, an error will arise. They are also ignored at the time of compilation.</p>
<h2 id="exception-hierarchy">Exception Hierarchy</h2>
<p>All exception classes are subtypes of the java.lang.Exception class. The exception class is a subclass of the Throwable class. Other than the exception class there is another subclass called Error which is derived from the Throwable class.</p>
<p>Errors are abnormal conditions that happen in case of severe failures, these are not handled by the Java programs. Errors are generated to indicate errors generated by the runtime environment. Example: JVM is out of memory. Normally, programs cannot recover from errors.</p>
<p>The Exception class has two main subclasses: IOException class and RuntimeException Class.</p>
<p><img alt="" src="https://www.tutorialspoint.com/java/images/exceptions1.jpg" /></p>
<p>Following is a list of most common checked and unchecked Java's Built-in Exceptions</p>
<h2 id="exceptions-methods">Exceptions Methods</h2>
<p>Following is the list of important methods available in the Throwable class.</p>
<table>
<tbody>
<tr>
<td>1</td>
<td><strong>public String getMessage()</strong><br />Returns a detailed message about the exception that has occurred. This message is initialized in the Throwable constructor.</td>
</tr>
<tr>
<td>2</td>
<td><strong>public Throwable getCause()</strong><br />Returns the cause of the exception as represented by a Throwable object.</td>
</tr>
<tr>
<td>3</td>
<td><strong>public String toString()</strong><br />Returns the name of the class concatenated with the result of getMessage().</td>
</tr>
<tr>
<td>4</td>
<td><strong>public void printStackTrace()</strong><br />Prints the result of toString() along with the stack trace to System.err, the error output stream.</td>
</tr>
<tr>
<td>5</td>
<td><strong>public StackTraceElement [] getStackTrace()</strong><br />Returns an array containing each element on the stack trace. The element at index 0 represents the top of the call stack, and the last element in the array represents the method at the bottom of the call stack.</td>
</tr>
<tr>
<td>6</td>
<td><strong>public Throwable fillInStackTrace()</strong><br />Fills the stack trace of this Throwable object with the current stack trace, adding to any previous information in the stack trace.</td>
</tr>
</tbody>
</table>

<h2 id="catching-exceptions">Catching Exceptions</h2>
<p>A method catches an exception using a combination of the <strong>try</strong> and <strong>catch</strong> keywords. A try/catch block is placed around the code that might generate an exception. Code within a try/catch block is referred to as protected code, and the syntax for using try/catch looks like the following</p>
<p><strong>Syntax</strong></p>
<pre><code class="java">try {
   // Protected code
}catch(ExceptionName e1) {
   // Catch block
}
</code></pre>

<p>The code which is prone to exceptions is placed in the try block. When an exception occurs, that exception occurred is handled by catch block associated with it. Every try block should be immediately followed either by a catch block or finally block.</p>
<p>A catch statement involves declaring the type of exception you are trying to catch. If an exception occurs in protected code, the catch block (or blocks) that follows the try is checked. If the type of exception that occurred is listed in a catch block, the exception is passed to the catch block much as an argument is passed into a method parameter.</p>
<p><strong>Example</strong></p>
<p>The following is an array declared with 2 elements. Then the code tries to access the 3rd element of the array which throws an exception.</p>
<pre><code class="java">// File Name : ExcepTest.java
import java.io.*;

public class ExcepTest {

   public static void main(String args[]) {
      try {
         int a[] = new int[2];
         System.out.println(&quot;Access element three :&quot; + a[3]);
      }catch(ArrayIndexOutOfBoundsException e) {
         System.out.println(&quot;Exception thrown  :&quot; + e);
      }
      System.out.println(&quot;Out of the block&quot;);
   }
}
</code></pre>

<p>This will produce the following result</p>
<pre><code>Exception thrown  :java.lang.ArrayIndexOutOfBoundsException: 3
Out of the block
</code></pre>

<h2 id="multiple-catch-blocks">Multiple Catch Blocks</h2>
<p>A try block can be followed by multiple catch blocks. The syntax for multiple catch blocks looks like the following</p>
<pre><code>try {
   // Protected code
}catch(ExceptionType1 e1) {
   // Catch block
}catch(ExceptionType2 e2) {
   // Catch block
}catch(ExceptionType3 e3) {
   // Catch block
}
</code></pre>

<p>The previous statements demonstrate three catch blocks, but you can have any number of them after a single try. If an exception occurs in the protected code, the exception is thrown to the first catch block in the list. If the data type of the exception thrown matches ExceptionType1, it gets caught there. If not, the exception passes down to the second catch statement. This continues until the exception either is caught or falls through all catches, in which case the current method stops execution and the exception is thrown down to the previous method on the call stack.</p>
<p><strong>Example</strong></p>
<p>Here is code segment showing how to use multiple try/catch statements.</p>
<pre><code class="java">try {
   file = new FileInputStream(fileName);
   x = (byte) file.read();
}catch(IOException i) {
   i.printStackTrace();
   return -1;
}catch(FileNotFoundException f) // Not valid! {
   f.printStackTrace();
   return -1;
}
</code></pre>

<h2 id="catching-multiple-type-of-exceptions">Catching Multiple Type of Exceptions</h2>
<p>Since Java 7, you can handle more than one exception using a single catch block, this feature simplifies the code. Here is how you would do it</p>
<pre><code class="java">catch (IOException|FileNotFoundException ex) {
   logger.log(ex);
   throw ex;
</code></pre>

<h2 id="the-throwsthrow-keywords">The Throws/Throw Keywords</h2>
<p>If a method does not handle a checked exception, the method must declare it using the throws keyword. The throws keyword appears at the end of a method's signature.</p>
<p>You can throw an exception, either a newly instantiated one or an exception that you just caught, by using the throw keyword.</p>
<p>Try to understand the difference between throws and throw keywords, throws is used to postpone the handling of a checked exception and throw is used to invoke an exception explicitly.</p>
<p>The following method declares that it throws a RemoteException </p>
<pre><code class="java">import java.io.*;
public class className {

   public void deposit(double amount) throws RemoteException {
      // Method implementation
      throw new RemoteException();
   }
   // Remainder of class definition
}
</code></pre>

<p>A method can declare that it throws more than one exception, in which case the exceptions are declared in a list separated by commas. For example, the following method declares that it throws a RemoteException and an InsufficientFundsException</p>
<pre><code class="java">import java.io.*;
public class className {

   public void withdraw(double amount) throws RemoteException, 
      InsufficientFundsException {
      // Method implementation
   }
   // Remainder of class definition
}
</code></pre>

<h2 id="the-finally-block">The Finally Block</h2>
<p>The finally block follows a try block or a catch block. A finally block of code always executes, irrespective of occurrence of an Exception.</p>
<p>Using a finally block allows you to run any cleanup-type statements that you want to execute, no matter what happens in the protected code.</p>
<p>A finally block appears at the end of the catch blocks and has the following syntax</p>
<p><strong>Syntax</strong></p>
<pre><code class="java">try {
   // Protected code
}catch(ExceptionType1 e1) {
   // Catch block
}catch(ExceptionType2 e2) {
   // Catch block
}catch(ExceptionType3 e3) {
   // Catch block
}finally {
   // The finally block always executes.
}

</code></pre>

<p><strong>Example</strong></p>
<pre><code class="java">public class ExcepTest {

   public static void main(String args[]) {
      int a[] = new int[2];
      try {
         System.out.println(&quot;Access element three :&quot; + a[3]);
      }catch(ArrayIndexOutOfBoundsException e) {
         System.out.println(&quot;Exception thrown  :&quot; + e);
      }finally {
         a[0] = 6;
         System.out.println(&quot;First element value: &quot; + a[0]);
         System.out.println(&quot;The finally statement is executed&quot;);
      }
   }
}
</code></pre>

<p>This will produce the following result </p>
<pre><code>Exception thrown  :java.lang.ArrayIndexOutOfBoundsException: 3
First element value: 6
The finally statement is executed
</code></pre>

<p>Note the following</p>
<ul>
<li>A catch clause cannot exist without a try statement.</li>
<li>It is not compulsory to have finally clauses whenever a try/catch block is present.</li>
<li>The try block cannot be present without either catch clause or finally clause.</li>
<li>Any code cannot be present in between the try, catch, finally blocks.</li>
</ul>
<h2 id="the-try-with-resources">The try-with-resources</h2>
<p>Generally, when we use any resources like streams, connections, etc. we have to close them explicitly using finally block. In the following program, we are reading data from a file using FileReader and we are closing it using finally block.</p>
<pre><code class="java">import java.io.File;
import java.io.FileReader;
import java.io.IOException;

public class ReadData_Demo {

   public static void main(String args[]) {
      FileReader fr = null;     
      try {
         File file = new File(&quot;file.txt&quot;);
         fr = new FileReader(file); char [] a = new char[50];
         fr.read(a);   // reads the content to the array
         for(char c : a)
         System.out.print(c);   // prints the characters one by one
      }catch(IOException e) {
         e.printStackTrace();
      }finally {
         try {
            fr.close();
         }catch(IOException ex) {       
            ex.printStackTrace();
         }
      }
   }
}
</code></pre>

<p>try-with-resources, also referred as automatic resource management, is a new exception handling mechanism that was introduced in Java 7, which automatically closes the resources used within the try catch block.</p>
<p>To use this statement, you simply need to declare the required resources within the parenthesis, and the created resource will be closed automatically at the end of the block. Following is the syntax of try-with-resources statement.</p>
<p><strong>Syntax</strong></p>
<pre><code class="java">try(FileReader fr = new FileReader(&quot;file path&quot;)) {
   // use the resource
   }catch() {
      // body of catch 
   }
}
</code></pre>

<p>Following is the program that reads the data in a file using try-with-resources statement.</p>
<p><strong>Example</strong></p>
<pre><code class="java">import java.io.FileReader;
import java.io.IOException;

public class Try_withDemo {

   public static void main(String args[]) {
      try(FileReader fr = new FileReader(&quot;E://file.txt&quot;)) {
         char [] a = new char[50];
         fr.read(a);   // reads the contentto the array
         for(char c : a)
         System.out.print(c);   // prints the characters one by one
      }catch(IOException e) {
         e.printStackTrace();
      }
   }
}
</code></pre>

<p>Following points are to be kept in mind while working with try-with-resources statement.</p>
<ul>
<li>To use a class with try-with-resources statement it should implement AutoCloseable interface and the close() method of it gets invoked automatically at runtime.</li>
<li>You can declare more than one class in try-with-resources statement.</li>
<li>While you declare multiple classes in the try block of try-with-resources statement these classes are closed in reverse order.</li>
<li>Except the declaration of resources within the parenthesis everything is the same as normal try/catch block of a try block.</li>
<li>The resource declared in try gets instantiated just before the start of the try-block.</li>
<li>The resource declared at the try block is implicitly declared as final.</li>
</ul>
<h2 id="user-defined-exceptions">User-defined Exceptions</h2>
<p>You can create your own exceptions in Java. Keep the following points in mind when writing your own exception classes âˆ’</p>
<ul>
<li>All exceptions must be a child of Throwable.</li>
<li>If you want to write a checked exception that is automatically enforced by the Handle or Declare Rule, you need to extend the Exception class.</li>
<li>If you want to write a runtime exception, you need to extend the RuntimeException class.</li>
</ul>
<p>We can define our own Exception class as below</p>
<pre><code>class MyException extends Exception {
}
</code></pre>

<p>You just need to extend the predefined Exception class to create your own Exception. These are considered to be checked exceptions. The following InsufficientFundsException class is a user-defined exception that extends the Exception class, making it a checked exception. An exception class is like any other class, containing useful fields and methods.</p>
<p><strong>Example</strong></p>
<pre><code class="java">// File Name InsufficientFundsException.java
import java.io.*;

public class InsufficientFundsException extends Exception {
   private double amount;

   public InsufficientFundsException(double amount) {
      this.amount = amount;
   }

   public double getAmount() {
      return amount;
   }
}
</code></pre>

<p>To demonstrate using our user-defined exception, the following CheckingAccount class contains a withdraw() method that throws an InsufficientFundsException.</p>
<pre><code class="java">// File Name CheckingAccount.java
import java.io.*;

public class CheckingAccount {
   private double balance;
   private int number;

   public CheckingAccount(int number) {
      this.number = number;
   }

   public void deposit(double amount) {
      balance += amount;
   }

   public void withdraw(double amount) throws InsufficientFundsException {
      if(amount &lt;= balance) {
         balance -= amount;
      }else {
         double needs = amount - balance;
         throw new InsufficientFundsException(needs);
      }
   }

   public double getBalance() {
      return balance;
   }

   public int getNumber() {
      return number;
   }
}
</code></pre>

<p>The following BankDemo program demonstrates invoking the deposit() and withdraw() methods of CheckingAccount.</p>
<pre><code class="java">// File Name BankDemo.java
public class BankDemo {

   public static void main(String [] args) {
      CheckingAccount c = new CheckingAccount(101);
      System.out.println(&quot;Depositing $500...&quot;);
      c.deposit(500.00);

      try {
         System.out.println(&quot;\nWithdrawing $100...&quot;);
         c.withdraw(100.00);
         System.out.println(&quot;\nWithdrawing $600...&quot;);
         c.withdraw(600.00);
      }catch(InsufficientFundsException e) {
         System.out.println(&quot;Sorry, but you are short $&quot; + e.getAmount());
         e.printStackTrace();
      }
   }
}
</code></pre>

<p>Compile all the above three files and run BankDemo. This will produce the following result </p>
<p><strong>Output</strong></p>
<pre><code>Depositing $500...

Withdrawing $100...

Withdrawing $600...
Sorry, but you are short $200.0
InsufficientFundsException
         at CheckingAccount.withdraw(CheckingAccount.java:25)
         at BankDemo.main(BankDemo.java:13)
</code></pre>

<h2 id="common-exceptions">Common Exceptions</h2>
<p>In Java, it is possible to define two catergories of Exceptions and Errors.</p>
<ul>
<li>JVM Exceptions âˆ’ These are exceptions/errors that are exclusively or logically thrown by the JVM. Examples: NullPointerException, ArrayIndexOutOfBoundsException, ClassCastException.</li>
<li>Programmatic Exceptions âˆ’ These exceptions are thrown explicitly by the application or the API programmers. Examples: IllegalArgumentException, IllegalStateException.</li>
</ul>
<h2 id="suggested-readings">Suggested Readings</h2>
<ul>
<li><a href="https://www.tutorialspoint.com/java/java_exceptions.htm">"Java Exceptions". 2016. <em>www.Tutorialspoint.Com</em>. https://www.tutorialspoint.com/java/java_exceptions.htm.</a></li>
</ul></div>
        </div>

        <footer class="col-md-12">
            <hr>
            <p>Documentation built with <a href="http://www.mkdocs.org/">MkDocs</a>.</p>
        </footer>
        <script>var base_url = '..';</script>
        <script data-main="../mkdocs/js/search.js" src="../mkdocs/js/require.js"></script>
        <script src="../js/base.js"></script>
        <script src="../components/underscore/underscore.js"></script>
        <script src="../components/magiz-c-book/src/gspreadsheet.js"></script>
        <script src="../components/magiz-c-paper/src/paper.js"></script>
        <script src="../components/magiz-c-course/src/course.js"></script>
        <script src="../components/magiz-c-benchmark/src/benchmark.js"></script>
        <script src="../components/magiz-c-benchmark/src/bootstrap-popup.js"></script>
        <script src="../components/magiz-c-book/src/book.js"></script>
        <script src="../components/magiz-c-video/src/video.js"></script>
        <script src="../components/jquery/dist/jquery.js"></script>
        <script src="../components/magiz-doc/doc.js"></script>
        <script src="../components/magiz-doc/footer.js"></script>
        <script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><div class="modal" id="mkdocs_search_modal" tabindex="-1" role="dialog" aria-labelledby="Search Modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Search</h4>
            </div>
            <div class="modal-body">
                <p>
                    From here you can search these documents. Enter
                    your search terms below.
                </p>
                <form role="form">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search..." id="mkdocs-search-query">
                    </div>
                </form>
                <div id="mkdocs-search-results"></div>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

    </body>
</html>
